language: c

os:
  - osx
  - linux
  - windows

# linux distro
dist: xenial

addons:
  apt:
    packages: ["libminizip-dev"]
  homebrew:
    packages: ["minizip"]

matrix:
  allow_failures:
    - os: windows

jobs:
  include:
  - stage: prepare
    os: windows
    script:
      - wget https://github.com/nmoinvaz/minizip/archive/2.8.4.zip
      - unzip 2.8.4.zip
      - cd minizip-2.8.4
      - mkdir build
      - cd build
      - cmake .. -DMZ_BUILD_TEST=ON -DMZ_BUILD_UNIT_TEST=ON -DCMAKE_BUILD_TYPE=Release
      - cmake --build . --config Release
      - export XLSXIO_CMAKE_ARGS="-DMINIZIP_DIR:PATH=$(pwd)"

  - stage: test
    script:
      - cmake . $XLSXIO_CMAKE_ARGS
      - cmake --build .
      - ./example_xlsxio_write
      - ls -lah example.xlsx
